# Generated by Django 5.0.3 on 2024-03-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=54)),
                ("margin", models.DecimalField(decimal_places=2, max_digits=54)),
                ("package_code", models.CharField(max_length=128)),
                ("encrypted_price", models.CharField(max_length=256)),
                ("encrypted_margin", models.CharField(max_length=256)),
                ("encrypted_package_code", models.CharField(max_length=256)),
            ],
        ),
    ]
