# Generated by Django 5.0.3 on 2024-03-29 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='desc',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='position',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
